version: '3.4'

services:
  terroristchecker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7081
      - ASPNETCORE_HTTPS_PORTS=7082
    ports:
      - "7081:7081"
      - "7082:7082"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
