@input=Abd al-Khaliq Badr al-Din al-Huthi
@yearOfBirth=1984

GET {{HostAddress}}/terrorists/search?input={{input}}&yearOfBirth={{yearOfBirth}}

###
GET {{HostAddress}}/terrorists/search?input={{input}}


